version: '3'

services:
  neo4j:
    image: neo4j:5.3.0
    restart: unless-stopped
    environment:
      NEO4J_AUTH: 'neo4j/password'
      NEO4J_dbms_security_auth__enabled: false
    ports:
      - '7474:7474'
      - '7687:7687'